# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: My deep learning
email: oformleno@gmail.com
author: Klepikov Konstantin
description: >- # this means to ignore newlines until "baseurl:"
  Блог про нейронные сети и машинное обучение
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://konstantinklepikov.github.io" # the base hostname & protocol for your site

exclude: [.vscode, readme.md, LICENSE, tag_generathor.py]

social:
  links:
    - https://t.me/KlepikovKonstantin
    - https://github.com/KonstantinKlepikov
    - https://facebook.com/konstatin.klepikov
lang: ru_RU

# twitter_username: 
facebook_username: konstatin.klepikov
telegram_username: KlepikovKonstantin
github_username: KonstantinKlepikov

# Build settings
markdown: kramdown
theme: jekyll-swiss
theme_color: magenta
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-environment-variables
  - jekyll-auto-image

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

github: [metadata]
highlighter: rouge