title: My deep learning
email: oformleno@gmail.com
author: Klepikov Konstantin
description: >- # this means to ignore newlines until "baseurl:"
  Блог про нейронные сети и машинное обучение
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://konstantinklepikov.github.io" # the base hostname & protocol for your site

social:
  links:
    - https://t.me/KlepikovKonstantin
    - https://github.com/KonstantinKlepikov
lang: ru_RU

# twitter_username:
telegram_username: KlepikovKonstantin
github_username: KonstantinKlepikov

# Build settings
markdown: kramdown
theme: jekyll-swiss
theme_color: magenta
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-environment-variables
  - jekyll-auto-image

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - .vscode
  - readme.md
  - LICENSE
  - tag_generathor.py
  - Makefile

github: [metadata]
highlighter: rouge